"""add column payment at order table

Revision ID: 0616c743668a
Revises: c57428435c70
Create Date: 2025-12-25 12:05:08.216955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0616c743668a'
down_revision: Union[str, Sequence[str], None] = 'c57428435c70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('payment_proof', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('payment_status', sa.String(), server_default='Belum Dibayar', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_status')
    op.drop_column('orders', 'payment_proof')
    op.drop_column('orders', 'payment_method')
    # ### end Alembic commands ###
