"""edit cart table

Revision ID: 2c34818f5314
Revises: 71944f09e3fe
Create Date: 2025-12-22 20:55:12.256970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c34818f5314'
down_revision: Union[str, Sequence[str], None] = '71944f09e3fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('carts_order_id_fkey'), 'carts', type_='foreignkey')
    op.create_foreign_key(None, 'carts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('carts', 'order_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.create_foreign_key(op.f('carts_order_id_fkey'), 'carts', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_column('carts', 'user_id')
    # ### end Alembic commands ###
