"""add colummn subtotal at cart table

Revision ID: ba215e8cc4bc
Revises: 2c34818f5314
Create Date: 2025-12-22 20:59:14.079600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba215e8cc4bc'
down_revision: Union[str, Sequence[str], None] = '2c34818f5314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('subtotal', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carts', 'subtotal')
    # ### end Alembic commands ###
